name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: 🧪 Tests & Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps & Playwright
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt playwright pytest-asyncio
          playwright install

      - name: Run tests & coverage
        run: |
          source venv/bin/activate
          pytest --maxfail=1 --disable-warnings -q \
                 --cov=app --cov=main --cov-report=xml

  build:
    name: 🚀 Build & Push Docker Image
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/601_module8:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/601_module8:${{ github.sha }}
